import os,json 
import openai
from openai import OpenAI
class Attacker:
    """
    This class checks the solidity source code and searches for patterns on the structured
    Based on a role of y/n questions, it makes 4 questions and returns the most frequent one
    It has a map of the categories, the prompts for each category and its features
    """
    def __init__(self,fn_name,fn_code):
        self.task_desc = """You are engaged in an exercise of ethical hacking, focusing on smart contracts. \
        In this scenario, you are assigned the role of an attacker who identifies and exploits vulnerabilities in smart contracts. \
        Your expertise lies in smart contract technology and cybersecurity. We will pose questions related to potential attacks on \
        smart contracts. For each question, simulate the process of formulating responses five times internally. Then, provide the \
        most common answer you derive from these simulations. Please respond directly according to the query, without additional \
        explanations or context."""

        #Task description (Message to request)
        #Whats the difference between the prompt and that? We could also call that a prompt
        self.task_desc = """You are engaged in an exercise of ethical hacking, focusing on smart contracts. \
        In this scenario, you are assigned the role of an attacker who identifies and exploits vulnerabilities in smart contracts. \
        Your expertise lies in smart contract technology and cybersecurity. We will pose questions related to potential attacks on \
        smart contracts. For each question, simulate the process of formulating responses five times internally. Then, provide the \
        most common answer you derive from these simulations. Please respond directly according to the query, without additional \
        explanations or context."""

        self.fn_name = fn_name
        self.code = fn_code
        #List of vulnerabilities category
        self.category = list()
        #Maps each category to a list of diagnostic questions
        self.category_to_features = dict()
        #Maps each category to the yes response corresponding to its features
        self.categorty = dict()
        #== to a final confirmation prompt
        #  ("Does this function exhibit unauthorized behavior? Answer Yes or No.")
        self.category_to_model = dict()
        #Loads all prompt def from a json file
        self.prompts = self.load_prompts()


    def load_prompts(self,directory = "Agents/prompt"):
        """
        This funtion reads the info from the category at the json file and
        adds the current category info to the object, loads the prompts and returns it, and 
        also put data into the object structure
        """
        
        os.makedirs(directory, exist_ok=True)
        #print(f"dir: {directory}")
        #print(os.listdir(directory))
        prompts = dict()
        for filename in os.listdir(directory):
            #print(f"Filenames: {filename}")
            if filename.endswith(".json"):
                filepath = os.path.join(directory,filename)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    data = json.load(f)
                prompts[data['category']] = data
                self.category.append(data['category'])
                self.category_to_features[data['category']] = data['feature']
                #stores the expected answers
                self.categorty[data['category']] = data['vul_ans']
                self.category_to_model[data['category']] = data['model']
            except Exception as e:
                print(f"failed to read {filename}: {e}")
        return prompts
    
    def query_feature(self,features)->str:
        """
        Template to build a question into a json-answer prompt
        """
        question_template = """Please review the provided smart contract code. Based on your analysis, answer the following questions regarding the contract's functionality. Present your answers in a JSON format, with each question's response being either "Yes" or "No". There is no need to explain your answer. Use the following template for your response: {"""


        for index, scenario in enumerate(features):
            question_template += f'"{index+1}": "Yes" or "No"'
            if index != len(features)-1:
                question_template += ', '

        question_template += f'}}.\nQuestions:\n'

        for index, feature in enumerate(features):
            question_template += f'"{index+1}": {feature}\n'

        question_template += f'\n{self.code}'

        return question_template
    
    def feature_matching(self):
        """
        Structure the questions with the prompt generated by query_feature(), each feature
        in the object, turns into a question with a first stage prompt
        """
        questions = list()
        #Collects all feature questions from all categories into one list.
        for value in self.category_to_features.values():
            questions.extend(value) 
        #returns a multiquestion prompt
        prompt_question = self.query_feature(questions)
        return prompt_question
    
    def get_ans_list(self):
        """
        Returns all the answers expected for each categoty and maps
        each vulnearabilities category to indexes
        """
        #List for all expected answers
        ans_list = list()
        #Placeholder to start the index in the index 1 (match numbered questions)
        ans_list.append("N/A")
        #to map question numbers to vulnerabilities categories
        ans_to_model = dict()
        #Question num
        i = 0
        for k, v in self.categorty.items():
            #K = category
            #V = answer expected
            ans_list.extend(v)
            #Maps each question number to its category
            for k in range(len(v)):
                i = i + 1
                ans_to_model[str(i)] = k
        return ans_list, ans_to_model
    

    def call_llm_agent_api(self, prompt_question: list) -> str:
        """
        Build prompt
            ↓
        Connect to Ollama
            ↓
        Send prompt to model
            ↓
        Generate response
            ↓
        Extract text
            ↓
        Clean text
            ↓
        Return result
        """
        try:
            client = OpenAI(
                base_url="http://localhost:11434/v1",
                api_key="ollama",
                timeout=60.0,
                max_retries=5
            )

            completion = client.chat.completions.create(
                model="qwen3:4b",
                messages=prompt_question,
                #Controls randomness (0 = deterministic)
                temperature=0,
                # Controls token sampling distribution
                top_p=1,
                #Forces valid json output
                response_format={"type": "json_object"}
            )
            #print(completion)

            ans = completion.choices[0].message.content
            return ans.strip()

        except openai.APIError as e:
            print(f"OpenAI API returned an API error: {e}")
            raise
        except openai.APIConnectionError as e:
            print(f"Falied to connect to OpenAI API: {e}")
            raise
        except Exception as e:
            print(f"Error at LLM API: {e}")
            raise
        
    def query(self):
        """
        Preparates a query, with the prompts, and the configurations 
        to the response obtained of the llm
        """
        """
        Gather all feature questions
                ↓
        Ask the LLM to answer Yes/No for each
                ↓
        Compare answers against known vulnerability patterns
                ↓
        Identify candidate vulnerability categories
                ↓
        Run confirmation prompts for each candidate
                ↓
        Return final list of confirmed vulnerabilities
        """
        res = list()

        try:
            prompt_message = list()
            prompt_task = self.task_desc
            prompt_message.append({"role" : "system","content": prompt_task})
            prompt_feature = self.feature_matching()

            prompt_message.append({"role":"user", "content" : prompt_feature})
            #Ask the llm y/n to each vulnerability
            answer_feature = self.call_llm_agent_api(prompt_message)

            prompt_message.pop()
            json_answer_feature = json.loads(answer_feature)
            #Known ans
            vul_ans, ans_to_model = self.get_ans_list()

            #Flags for each vulnerability
            flag_price = False
            flag_calculate = False
            flag_privilege = False
            flag_control = False

            #track each vul was found
            for i in range(1,14):
                if json_answer_feature[str(i)] == vul_ans[i]:
                    if ans_to_model[str(i)] == "Incorrect Control Mechanism":
                        flag_control = True
                    elif ans_to_model[str(i)] == "Insecure Calculating Logic":
                        flag_calculate = True
                    elif ans_to_model[str(i)] == "Price Oracle Manipulation":
                        flag_price = True
                    elif ans_to_model[str(i)] == "Unauthorized Behavior":
                        flag_privilege = True
            #Confirmation run for each vulnerability found in the analisys
            if flag_control: 
                prompt_model = self.category_to_model["Incorrect Control Mechanism"]
                prompt_message.append({"role" : "user", "content" : prompt_model})
                answer_model = self.call_llm_agent_api(prompt_message)
                if answer_model == "Yes":
                    res.append("Incorrect Control Mechanism")
                prompt_message.pop()
            if flag_calculate:
                prompt_model = self.category_to_model["Insecure_Calculating_Logic"]
                prompt_message.append({"role": "user", "content": prompt_model})
                answer_model = self.call_llm_agent_api(prompt_message)
                if answer_model == "Yes":
                    res.append("Insecure Calculating Logic")
                prompt_message.pop()

            if flag_price:
                prompt_model = self.category_to_model["Price Oracle Manipulation"]
                prompt_message.append({"role": "user", "content": prompt_model})
                answer_model = self.call_llm_agent_api(prompt_message)
                if answer_model == "Yes":
                    res.append("Price Oracle Manipulation")
                prompt_message.pop()

            if flag_privilege:
                prompt_model = self.category_to_model["Unauthorized Behavior"]
                prompt_message.append({"role": "user", "content": prompt_model})
                answer_model = self.call_llm_agent_api(prompt_message)
                if answer_model == "Yes":
                    res.append("Unauthorized Behavior")
                prompt_message.pop()
        except Exception as e:
            print(e)
        
        return res