import os,json 
from openai import OpenAI
class Attacker:
    """
    This class checks the solidity source code and searches for patterns on the structured
    Based on a role of y/n questions, it makes 4 questions and returns the most frequent one
    It has a map of the categories, the prompts for each category and its features
    """
    def __init__(self,fn_name,fn_code):
        self.task_desc = """You are engaged in an exercise of ethical hacking, focusing on smart contracts. \
        In this scenario, you are assigned the role of an attacker who identifies and exploits vulnerabilities in smart contracts. \
        Your expertise lies in smart contract technology and cybersecurity. We will pose questions related to potential attacks on \
        smart contracts. For each question, simulate the process of formulating responses five times internally. Then, provide the \
        most common answer you derive from these simulations. Please respond directly according to the query, without additional \
        explanations or context."""

        #Task description (Message to request)
        #Whats the difference between the prompt and that? We could also call that a prompt
        self.task_desc = """You are engaged in an exercise of ethical hacking, focusing on smart contracts. \
        In this scenario, you are assigned the role of an attacker who identifies and exploits vulnerabilities in smart contracts. \
        Your expertise lies in smart contract technology and cybersecurity. We will pose questions related to potential attacks on \
        smart contracts. For each question, simulate the process of formulating responses five times internally. Then, provide the \
        most common answer you derive from these simulations. Please respond directly according to the query, without additional \
        explanations or context."""

        self.fn_name = fn_name
        self.code = fn_code
        #List of vulnerabilities category
        self.category = list()
        #Maps each category to a list of diagnostic questions
        self.category_to_features = dict()
        #Maps each category to the yes response corresponding to its features
        self.categorty = dict()
        #== to a final confirmation prompt
        #  ("Does this function exhibit unauthorized behavior? Answer Yes or No.")
        self.category_to_model = dict()
        #Loads all prompt def from a json file
        self.prompts = self.load_prompts()


    def load_prompts(self,directory = "prompts/attacker/prompt"):
        """
        This funtion reads the info from the category at the json file and
        adds the current category info to the object, loads the prompts and returns it, and 
        also put data into the object structure
        """
        
        os.makedirs(directory, exist_ok=True)

        prompts = dict()
        for filename in os.listdir(directory):
            if filename.endswith(".json"):
                filepath = os.path.join(directory,filename)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    data = json.load(f)
                prompts[data['category']] = data
                self.category.append(data['category'])
                self.category_to_features[data['category']] = data['feature']
                #stores the expected answers
                self.categorty[data['category']] = data['vul_ans']
                self.category_to_model[data['category']] = data['model']
            except Exception as e:
                print(f"failed to read {filename}: {e}")
        return prompts
    
    def query_feature(self,features)->str:
        """
        Template to build a question into a json-answer prompt
        """
        question_template = """Please review the provided smart contract code. Based on your analysis, answer the following questions regarding the contract's functionality. Present your answers in a JSON format, with each question's response being either "Yes" or "No". There is no need to explain your answer. Use the following template for your response: {"""


        for index, scenario in enumerate(features):
            question_template += f'"{index+1}": "Yes" or "No"'
            if index != len(features)-1:
                question_template += ', '

        question_template += f'}}.\nQuestions:\n'

        for index, feature in enumerate(features):
            question_template += f'"{index+1}": {feature}\n'

        question_template += f'\n{self.code}'

        return question_template
    
    def feature_matching(self):
        """
        Structure the questions with the prompt generated by query_feature(), each feature
        in the object, turns into a question with a first stage prompt
        """
        questions = list()
        #Collects all feature questions from all categories into one list.
        for value in self.category_to_features.values():
            questions.extend(value) 
        #returns a multiquestion prompt
        prompt_question = self.query_feature(questions)
        return prompt_question
    
    def get_ans_list(self):
        """
        Returns all the answers expected for each categoty and maps
        each vulnearabilities category to indexes
        """
        #List for all expected answers
        ans_list = list()
        #Placeholder to start the index in the index 1 (match numbered questions)
        ans_list.append("N/A")
        #to map question numbers to vulnerabilities categories
        ans_to_model = dict()
        #Question num
        i = 0
        for k, v in self.categorty.items():
            #K = category
            #V = answer expected
            ans_list.extend(v)
            #Maps each question number to its category
            for k in range(len(v)):
                i = i + 1
                ans_to_model[str(i)] = k
        return ans_list, ans_to_model
    
    
        
    
